# Generated by Django 3.1.5 on 2021-09-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_social_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
